version: '3.10'

x-base-image: &base-image
  restart: always
  env_file:
    - .env
  networks:
    default: {}
  logging:
    options:
      max-size: "10m"
      max-file: "3"


services:
  db:
    <<: *base-image
    image: "postgres:14.1-alpine"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5453:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
